---
- name: Install docker dependencies
  dnf: 
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install the lastest Docker
  dnf:
    name: docker-ce
    state: present

- name: Make sure Docker deamon is running 
  systemd:
    name: docker 
    state: started
    enabled: yes

- name: Add existing 'centos' user to group docker
  user:
    name: centos
    groups: docker
    append: yes

- name: 'Create container for app {{ service_name }}'
  docker_container:
    name: "{{ service_name }}"
    image: "{{ docker_image_name }}"
    state: started
    pull: yes
    recreate: yes
    detach: yes
    published_ports:
      - "{{ PORT }}:{{ PORT }}"
    env:
      PORT: "{{ PORT }}" # applies for both apps.
      BACK_HOST: "{{ api_lb_ip | default('') }}" # default for api which does not need it.
