---
- name: Clone api repo
  git:
    repo: "https://github.com/juan-ruiz/movie-analyst-api.git"
    dest: "{{ repo_dir }}"

- name: pm2 configuration
  include_role:
    name: common
    tasks_from: pm2_config
