---
- name: Set api load balancer variable
  lineinfile:
    dest: "~/.bashrc"
    line: "export BACK_HOST={{ api_lb_ip }}"
    regexp: "export BACK_HOST={{ api_lb_ip }}"
    insertafter: 'EOF'
    state: present
  
- name: Source the bashrc file
  shell: 
    cmd: "source ~/.bashrc"
    warn: no

- name: Clone api repo
  git:
    repo: "https://github.com/juan-ruiz/movie-analyst-ui.git"
    dest: "{{ repo_dir }}"

- name: pm2 configuration
  include_role:
    name: common
    tasks_from: pm2_config
